apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwl-pod-limmited
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: wwwl-pod-limmited
  template:
    metadata:
      name: wwwl-pod-limmited
      labels:
        app: wwwl-pod-limmited
    spec:
      # Achtung seit v1.34 gehts auch auf Podlevel
      # und damit f√ºr alle Pods. Sinnig?
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
          #ephemeral-storage: "10Mi"   Das geht nur auf containers ...
        limits:
          cpu: 50m
          memory: 50Mi
          #ephemeral-storage: "10Mi"   Das geht nur auf containers
      terminationGracePeriodSeconds: 2
      containers:
        - name: image1
          image: erkules/nginxhostname:v1
