---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: simplests-pdb
spec:
  minAvailable: 3
  #  maxUnavailable: 1
  selector:
    matchLabels:
      app: wwwanti
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwanti
spec:
  replicas: 3
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wwwanti
  template:
    metadata:
      name: wwwanti
      labels:
        app: wwwanti
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - wwwanti
      #       topologyKey: kubernetes.io/hostname
      containers:
      - name: image1
        image: erkules/nginxhostname

