apiVersion: apps/v1
kind: Deployment
metadata:
  name: configaro
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: configaro
  template:
    metadata:
      name: configaro
      labels:
        app: configaro
    spec:
      # Achtung seit v1.34 gehts auch auf Podlevel
      # und damit f√ºr alle Pods. Sinnig?
      terminationGracePeriodSeconds: 2
      containers:
        - name: image1
          image: erkules/nginxhostname:v1
          env:
          - name: umgebung
            valueFrom:
              configMapKeyRef:
                name: configaro
                key: hallo
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
              ephemeral-storage: "10Mi"
            limits:
              cpu: 50m
              memory: 50Mi
              ephemeral-storage: "10Mi"
